language: objective-c

# These Travis settings are specific to `language: objective-c`
xcode_workspace: Fonts.xcworkspace
xcode_scheme: Fonts
xcode_sdk: iphonesimulator

env:

  # global environment variables apply to every build in the build matrix
  global:

    # CocoaPods requires the environment to be using UTF-8 encoding.
    - LANG=en_US.UTF-8

    # Only enable tests if this is a pull request. You are welcome to modify the logic here, but the result
    # must be to assign a valid xctool build action to TWT_XCODE_BUILD_ACTION
    - TWT_XCODE_BUILD_ACTION=$(if [ "$TRAVIS_PULL_REQUEST" != 'false' ]; then echo 'test'; else echo 'build'; fi)

    # Only distribute if this is a commit into master and not a pull request. You are welcome to modify the
    # logic here, but the result must be to assign '0' (true) or '1' (false) to TWT_SHOULD_DISTRIBUTE
    - TWT_SHOULD_DISTRIBUTE=$([ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" = 'false' ]; echo $?)

    # TWT_DROPBOX_DISTRIBUTION_DEPENDENCIES_URL
    - secure: "ezYaYyovtdPC3ViIk3+NsKHJqFTY+QuzMIKg/40UX6KiQ/47Tz+Eqi+NEQexZwxtMhV3zHXq1TpZsK6MK9FhAIB1N/VRa/m333gFbv6bAjfNXGsRdPcoNKiGW2ELSGsMwxnSG40ETLmVOvbitPC5aI1E1gX/t1noCdI7cUiaxKI="

    # TWT_CODESIGNING_KEY_PASSWORD
    # Important: http://docs.travis-ci.com/user/encryption-keys/#Note-on-escaping-certain-symbols
    - secure: "NepygLrOJ+tG5NAcQR7EuoSaXF04gd9OjORzRZVcInlqsWaFDf8VHZnw107ngoNTB+FfLGAjzdoF6XYD/oaBkpDgKveGa2dU6JDbDZM5XB+GL89+IMuDrUKRRR9qE8AAKvrHptZL3QTdFKrWKJTijrtB4KryTtE2uInrHYgQusE="

before_install:

  # Set the Ruby version to work around https://github.com/travis-ci/travis-ci/issues/2152
  # This also makes it so that we can specify the ruby version in a single place:
  # .ruby-version. This command cannot go in before_install.sh because it works by
  # modifying the environment
  - rvm use .

  # Run travis-scripts/before_install.sh
  # You can modify its contents to customize the setup that is performed here
  - bash -v travis-scripts/before_install.sh

install:

  # Run travis-scripts/install.sh
  # You can modify its contents to customize the setup that is performed here
  - chmod +x ./travis-scripts/install.sh
  - ./travis-scripts/install.sh

# Run travis-scripts/install.sh
# You can modify its contents to customize the setup that is performed here
install: bash -v travis-scripts/install.sh

# Run travis-scripts/script.sh
# You can modify its contents if needed
script: bash -v travis-scripts/script.sh

# Run travis-scripts/after_success.sh
# You can modify its contents if needed
after_success: bash -v travis-scripts/after_success.sh
